### ISSUE TITLE
 IndexError when plot dynamic patterns 

### ISSUE THREAD

**Issue by biobai** [simonvh/fluff#40]
Hi,
I am impressed by the dynamic patterns parts in fluff. 
I can get the dynamic plot from the example, but this error came up when I use own date:
##CMD
$ fluff heatmap -f tsses_2kb_new.bed -d WT_H2A_Z.sort.bam WT_H3K4me3.sort.bam WT_H3K27me3.sort.bam WT_pol.sort.bam -C k -k 5 -g -M Pearson -o kmeans5_dynamics

Pearson distance method
Loading data
K-means clustering
Loading data
Traceback (most recent call last):
  File "/root/anaconda2/bin/fluff", line 4, in <module>
    __import__('pkg_resources').run_script('biofluff==2.0.1', 'fluff')
  File "/root/anaconda2/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script
  File "/root/anaconda2/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1484, in run_script
  File "/root/anaconda2/lib/python2.7/site-packages/biofluff-2.0.1-py2.7.egg-info/scripts/fluff", line 327, in <module>
    args.func(args)
  File "/root/anaconda2/lib/python2.7/site-packages/fluff/commands/heatmap.py", line 181, in heatmap
    for (chrom, start, end, gene, strand), cluster in zip(array(regions, dtype="object")[ind], array(labels)[ind]):
IndexError: index 27201 is out of bounds for axis 0 with size 27200

##Bed file attached here
[tsses_2kb_new.bed.txt](https://github.com/simonvh/fluff/files/262770/tsses_2kb_new.bed.txt)

Please help me!

Youhuang Bai

**Comment by simonvh** [comment]
Hi Youhang, we'll have a look and see if we can find the issue.

**Comment by georgeg9** [comment]
Hello Youhuang,

The issue has been fixed.. I submitted a pull request to bioconda and i expect it to be merged soon.

George

**Comment by biobai** [comment]
Great thanks to you, George!
