### ISSUE TITLE
list index out of range error !

### ISSUE THREAD

**Issue by AlicePsyche** [simonvh/fluff#47]
Hi, 

I am using fluff to plot heatmap: `fluff heatmap -f mergePeaks.bed -d bed1 bed2 bed3 bed4 bed5  -C k -k 5 -g -M Pearson -p 12 -o kmeans5_dynamics` But it comes with an error :

```
Traceback (most recent call last):
  File "/software/anaconda/bin/fluff", line 4, in <module>
    __import__('pkg_resources').run_script('biofluff==2.0.2', 'fluff')
  File "/software/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script

  File "/software/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1484, in run_script

  File "/software/anaconda/lib/python2.7/site-packages/biofluff-2.0.2-py2.7.egg-info/scripts/fluff", line 327, in <module>
    args.func(args)
  File "/software/anaconda/lib/python2.7/site-packages/fluff/commands/heatmap.py", line 136, in heatmap
    clus = hstack([norm_data[t] for i, t in enumerate(tracks) if (not pick or i in pick)])
  File "/software/anaconda/lib/python2.7/site-packages/numpy/core/shape_base.py", line 277, in hstack
    if arrs[0].ndim == 1:
IndexError: list index out of range
```

Could you please give some guides where I can debug on ? 

Thanks in advance !

**Comment by simonvh** [comment]
I see you are using the `-p` argument, so I guess the aim is to cluster only on the first two data files (`bed1` and `bed2`). In that case the argument should be `-p 1,2` instead of `-p 12`, so comma-separated. The error message here could definitely be more clear :).

**Comment by AlicePsyche** [comment]
Ashamed of myself....Actually, I meant 12 CPUs... `-P`  not `-p`. Really sorry for bothering you...I would be more careful next time. Thanks !

**Comment by simonvh** [comment]
No problem at all!
