### ISSUE TITLE
error - invalid DISPLAY variable

### ISSUE THREAD

**Issue by ltosti** [simonvh/fluff#55]
Hi,

when I try to run fluff either on my data or on the example data I get this error:

Traceback (most recent call last):
  File "anaconda/bin/fluff", line 4, in <module>
    __import__('pkg_resources').run_script('biofluff==2.1.0', 'fluff')
  File "anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script
  File "anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1484, in run_script
  File "anaconda/lib/python2.7/site-packages/biofluff-2.1.0-py2.7.egg-info/scripts/fluff", line 9, in <module>
    args.func(args)
  File "anaconda/lib/python2.7/site-packages/fluff/commands/heatmap.py", line 235, in heatmap
    heatmap_plot(data, ind[::-1], outfile, tracks, titles, colors, bgcolors, scale, tscale, labels, fontsize)
  File "anaconda/lib/python2.7/site-packages/fluff/plot.py", line 85, in heatmap_plot
    fig = plt.figure(figsize=(plot_width, plot_height))
  File "anaconda/lib/python2.7/site-packages/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 76, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt4.py", line 68, in __init__
    _create_qApp()
  File "anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 138, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable

Any suggestion?

Thanks!

**Comment by simonvh** [comment]
This has to do with the matplotlib backend. You should have a file called `matplotlibrc` in your anaconda environment. Most likely it is called:

```
anaconda/lib/python2.7/site-packages/matplotlib/mpl-data/matplotlibrc
```

Can you find the following line in that file: 

```
backend      : Qt4Agg
```

and change that to:

```
backend      : Agg
```

This should fix the problem. For more information, see [here](http://matplotlib.org/users/customizing.html).

**Comment by ltosti** [comment]
Hi Simon,

thanks, indeed it fixed it!
