### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by biomm** [simonvh/fluff#58]
Dear Simon,

I have installed fluff using conda from Anaconda2 without any error. Afterwards, I have also added bioconda in channel and created an env for biofluff using:
$ conda config --add channels bioconda
$ conda create -n analysis biofluff

Than I tried to run fluff heatmap command, I am getting this error:

$ fluff heatmap -f example_peaks.bed -d H1_DNase.bam H1_H3K27ac.bam -o H1

#####################
Traceback (most recent call last):
  File "/home/user/dependencies/anaconda2/envs/analysis/bin/fluff", line 4, in <module>
    __import__('pkg_resources').run_script('biofluff==2.1.0', 'fluff')
  File "/home/user/.local/lib/python2.7/site-packages/distribute-0.6.10-py2.7.egg/pkg_resources.py", line 461, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/user/.local/lib/python2.7/site-packages/distribute-0.6.10-py2.7.egg/pkg_resources.py", line 1194, in run_script
    execfile(script_filename, namespace, namespace)
  File "/fsimb/imbc_home/user/.local/lib/python2.7/site-packages/biofluff-2.1.0-py2.7.egg/EGG-INFO/scripts/fluff", line 4, in <module>
    from fluff.parse import parse_args
  File "/home/user/.local/lib/python2.7/site-packages/biofluff-2.1.0-py2.7.egg/fluff/parse.py", line 4, in <module>
    from fluff import commands
  File "/home/user/.local/lib/python2.7/site-packages/biofluff-2.1.0-py2.7.egg/fluff/commands/__init__.py", line 10, in <module>
    m = __import__("{0}.{1}".format(__name__, cmdname), globals(), locals(), [cmdname], -1)
  File "/home/user/.local/lib/python2.7/site-packages/biofluff-2.1.0-py2.7.egg/fluff/commands/bandplot.py", line 5, in <module>
    import pysam
  File "/home/user/.local/lib/python2.7/site-packages/RSeQC-2.3.7-py2.7-linux-x86_64.egg/pysam/__init__.py", line 1, in <module>
    from csamtools import *
ImportError: /home/user/.local/lib/python2.7/site-packages/RSeQC-2.3.7-py2.7-linux-x86_64.egg/csamtools.so: undefined symbol: PyUnicodeUCS2_DecodeUTF8
#####################

I would like to request you for your help to solve this error and run the fluff command successfully. I would also appreciate any kind of solution to try from the users as well.
Thanks in advance.

Regards,
M

**Comment by simonvh** [comment]
Can you give some more details on home exactly you installed fluff? From the error messages it seems that fluff is not installed in your anaconda directory but in `~/.local`. This points towards a installation with `pip install --user`.

**Comment by biomm** [comment]
I installed it using:
conda install biofluff -c bioconda

Fetching package metadata ...........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/mallick/dependencies/anaconda2:
#
biofluff                  2.1.0                    py27_0    bioconda

I am installing this in my drive on university server. I am not the root. So is this a problem of not using --user option !!

**Comment by biomm** [comment]
I installed it using:
/home/user/../anaconda2/bin/conda install biofluff -c bioconda

Fetching package metadata ...........
Solving package specifications: .

All requested packages already installed.
packages in environment at /home/user/../anaconda2:

biofluff 2.1.0 py27_0 bioconda

I am installing this in my drive on university server. I am not the root. So is this a problem of not using --user option !!

**Comment by simonvh** [comment]
Can you show me the output of the following commands?:
`$ which python`
`$ which conda`
`$ which fluff`

I just don't understand why fluff is installed in `/home/user/.local/lib/python2.7/site-packages/biofluff-2.1.0-py2.7.egg/`, when it should be in the anaconda directory.

**Comment by simonvh** [comment]
Any updates or can we close the issue?

**Comment by simonvh** [comment]
I'm closing the issue, feel free to re-open if you still encounter problems.
