### ISSUE TITLE
Can't install with pip: No matching distribution found for Pycluster

### ISSUE THREAD

**Issue by zfrenchee** [simonvh/fluff#71]
Hi @simonvh, 

I tried to follow the [install instructions in the docs](http://fluff.readthedocs.io/en/latest/installation.html#alternative-using-pip) but they didn't quite work for me. 

```
~ » pip2 --version
pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
------------------------------------------------------------
~ » pip2 install biofluff
Collecting biofluff
  Using cached biofluff-2.1.4-py2-none-any.whl
Collecting Pycluster (from biofluff)
  Could not find a version that satisfies the requirement Pycluster (from biofluff) (from versions: )
No matching distribution found for Pycluster (from biofluff)
```

What am I doing wrong?

**Comment by zfrenchee** [comment]
I also tried installing from source, but got this error: 

```
sudo python setup.py install
...
...lots of stuff...
...
zip_safe flag not set; analyzing archive contents...
pyBigWigTest.test: module references __file__
No eggs found in /tmp/easy_install-pwIdEF/pyBigWig-0.3.10/egg-dist-tmp-lElZLr (setup script problem?)
error: The 'pyBigWig' distribution was not found and is required by biofluff
```

**Comment by simonvh** [comment]
Ok, so apparently the installation instructions are out of date, I will have to check them. In the mean time, your best way forward is to use [bioconda](http://bioconda.github.io/), which I can highly recommend. See also here: https://www.biorxiv.org/content/early/2017/10/27/207092

After you have followed the bioconda setup instructions you can install fluff with the following command:

`$ conda install biofluff`

**Comment by zfrenchee** [comment]
@simonvh 

```
~ » conda create -n fluff python=2 biofluff                                                                      alex@alexs-mbp
Solving environment: - \ bdone

## Package Plan ##

  environment location: /Users/alex/miniconda2/envs/fluff

  added / updated specs:
    - biofluff
    - python=2


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    clangdev-5.0.0             |        default_0        73.2 MB  conda-forge
    pysam-0.14.0               | py27_htslib1.7_2         2.0 MB  bioconda
    llvm-meta-5.0.0            |                0           3 KB  conda-forge
    icu-58.2                   |                0        22.7 MB  conda-forge
    sqlite-3.20.1              |                2         1.4 MB  conda-forge
    wheel-0.30.0               |           py27_2          66 KB  conda-forge
    libiconv-1.15              |                0         1.3 MB  conda-forge
    zlib-1.2.11                |                0          95 KB  conda-forge
    python-2.7.14              |                4         9.7 MB  conda-forge
    ncurses-5.9                |               10         1.1 MB  conda-forge
    pip-9.0.1                  |           py27_1         1.7 MB  conda-forge
    tk-8.6.7                   |                0         3.0 MB  conda-forge
    setuptools-38.5.1          |           py27_0         510 KB  conda-forge
    libxml2-2.9.7              |                0         1.9 MB  conda-forge
    libcxx-5.0.0               |                0         1.1 MB  conda-forge
    readline-7.0               |                0         383 KB  conda-forge
    six-1.11.0                 |           py27_1          20 KB  conda-forge
    llvmdev-5.0.0              |        default_1       114.7 MB  conda-forge
    ------------------------------------------------------------
                                           Total:       234.9 MB

The following NEW packages will be INSTALLED:

    backports:                     1.0-py27_1              conda-forge
    backports.functools_lru_cache: 1.5-py27_0              conda-forge
    backports_abc:                 0.5-py27_0              conda-forge
    bcftools:                      1.6-1                   bioconda
    bedtools:                      2.27.1-1                bioconda
    biofluff:                      2.1.3-py27_0            bioconda
    bzip2:                         1.0.6-1                 conda-forge
    ca-certificates:               2018.1.18-0             conda-forge
    certifi:                       2018.1.18-py27_0        conda-forge
    clangdev:                      5.0.0-default_0         conda-forge
    colorbrewer:                   0.1.1-py27_1            bioconda
    curl:                          7.55.1-0                conda-forge
    cycler:                        0.10.0-py27_0           conda-forge
    freetype:                      2.8.1-0                 conda-forge
    functools32:                   3.2.3.2-py27_2          conda-forge
    htseq:                         0.9.1-py27_0            bioconda
    htslib:                        1.7-0                   bioconda
    icu:                           58.2-0                  conda-forge
    intel-openmp:                  2018.0.0-h8158457_8
    krb5:                          1.14.2-0                conda-forge
    libcxx:                        5.0.0-0                 conda-forge
    libgfortran:                   3.0.1-h93005f0_2
    libiconv:                      1.15-0                  conda-forge
    libpng:                        1.6.34-0                conda-forge
    libssh2:                       1.8.0-2                 conda-forge
    libxml2:                       2.9.7-0                 conda-forge
    llvm-meta:                     5.0.0-0                 conda-forge
    llvmdev:                       5.0.0-default_1         conda-forge
    matplotlib:                    2.1.2-py27_0            conda-forge
    mkl:                           2018.0.1-hfbd8650_4
    ncurses:                       5.9-10                  conda-forge
    numpy:                         1.13.3-py27h8a80b8c_2
    openssl:                       1.0.2n-0                conda-forge
    pandas:                        0.22.0-py27_0           conda-forge
    pip:                           9.0.1-py27_1            conda-forge
    pybedtools:                    0.7.10-py27_2           bioconda
    pybigwig:                      0.3.10-np113py27_0      bioconda
    pycluster:                     1.54-py27_0             bioconda
    pyparsing:                     2.2.0-py27_0            conda-forge
    pysam:                         0.14.0-py27_htslib1.7_2 bioconda
    python:                        2.7.14-4                conda-forge
    python-dateutil:               2.3-py27_0              bioconda
    pytz:                          2018.3-py_0             conda-forge
    readline:                      7.0-0                   conda-forge
    samtools:                      1.7-1                   bioconda
    scipy:                         1.0.0-py27h793f721_0
    setuptools:                    38.5.1-py27_0           conda-forge
    singledispatch:                3.4.0.3-py27_0          conda-forge
    six:                           1.11.0-py27_1           conda-forge
    sqlite:                        3.20.1-2                conda-forge
    ssl_match_hostname:            3.5.0.1-py27_1          conda-forge
    subprocess32:                  3.2.7-py27_0            conda-forge
    tk:                            8.6.7-0                 conda-forge
    tornado:                       4.5.3-py27_0            conda-forge
    wheel:                         0.30.0-py27_2           conda-forge
    xz:                            5.2.3-0                 conda-forge
    zlib:                          1.2.11-0                conda-forge

Proceed ([y]/n)? y
Invalid choice: subl y
Proceed ([y]/n)? y


Downloading and Extracting Packages
clangdev 5.0.0: ######################################################################################################## | 100%
pysam 0.14.0: ########################################################################################################## | 100%
llvm-meta 5.0.0: ####################################################################################################### | 100%
icu 58.2: ############################################################################################################## | 100%
sqlite 3.20.1: ######################################################################################################### | 100%
wheel 0.30.0: ########################################################################################################## | 100%
libiconv 1.15: ######################################################################################################### | 100%
zlib 1.2.11: ########################################################################################################### | 100%
python 2.7.14: ######################################################################################################### | 100%
ncurses 5.9: ########################################################################################################### | 100%
pip 9.0.1: ############################################################################################################# | 100%
tk 8.6.7: ############################################################################################################## | 100%
setuptools 38.5.1: ##################################################################################################### | 100%
libxml2 2.9.7: ######################################################################################################### | 100%
libcxx 5.0.0: ########################################################################################################## | 100%
readline 7.0: ########################################################################################################## | 100%
six 1.11.0: ############################################################################################################ | 100%
llvmdev 5.0.0: ######################################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use:
# > source activate fluff
#
# To deactivate an active environment, use:
# > source deactivate
#

------------------------------------------------------------
~ » source activate fluff                                                                                        alex@alexs-mbp
Traceback (most recent call last):
  File "/Users/alex/miniconda2/lib/python2.7/site-packages/conda/gateways/logging.py", line 64, in emit
    msg = self.format(record)
  File "/Users/alex/miniconda2/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/Users/alex/miniconda2/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/Users/alex/miniconda2/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
  File "/Users/alex/miniconda2/lib/python2.7/site-packages/conda/__init__.py", line 43, in __repr__
    return '%s: %s' % (self.__class__.__name__, text_type(self))
  File "/Users/alex/miniconda2/lib/python2.7/site-packages/conda/__init__.py", line 47, in __str__
    return text_type(self.message % self._kwargs)
ValueError: unsupported format character '{' (0x7b) at index 527
Logged from file exceptions.py, line 770
```

**Comment by simonvh** [comment]
@zfrenchee this seems to be a conda error, one that I have not seen before. However, this issue seems to be similar: https://github.com/conda/conda/issues/6739  Can you see if that helps solving your problem. I'm sorry installing fluff is being such a hassle for you :-(.

**Comment by simonvh** [comment]
Closing due to inactivity, feel free to re-open if necessary.
