### ISSUE TITLE
UnboundLocalError: local variable 'feature' referenced before assignment

### ISSUE THREAD

**Issue by hhhcce** [simonvh/fluff#74]
**To whom it may concern, 

I was trying to use fluff to plot a dynamic heatmap. I ran the following code:**

fluff heatmap -f Merged_peaks_MACS0.10_noPeaklistinput_CallpeaksbyRep12345_02062018.bed -d A.bed B.bed C.bed D.bed -C k -k 6 -g -M Pearson -o Merged_peaks_MACS0.10_noPeaklistinput_CallpeaksbyRep12345_02062018_Rep12only_k6

**And got the following errors:
Is there a way to solve this?**

Warning: Running fluff with too many files might make you system use enormous amount of memory!
Pearson distance method
Loading data
Error loading data in parallel, trying serial
Error: local variable 'feature' referenced before assignment
Traceback (most recent call last):
  File "/home/ceang/anaconda3/envs/biofluff/bin/fluff", line 4, in <module>
    __import__('pkg_resources').run_script('biofluff==2.1.3', 'fluff')
  File "/home/ceang/anaconda3/envs/biofluff/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/ceang/anaconda3/envs/biofluff/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/home/ceang/anaconda3/envs/biofluff/lib/python2.7/site-packages/biofluff-2.1.3-py2.7.egg-info/scripts/fluff", line 9, in <module>
    args.func(args)
  File "/home/ceang/anaconda3/envs/biofluff/lib/python2.7/site-packages/fluff/commands/heatmap.py", line 147, in heatmap
    fragmentsize, dynam, guard)
  File "/home/ceang/anaconda3/envs/biofluff/lib/python2.7/site-packages/fluff/commands/heatmap.py", line 125, in load_data
    fragmentsize, dynam, guard)
  File "/home/ceang/anaconda3/envs/biofluff/lib/python2.7/site-packages/fluff/fluffio.py", line 183, in load_heatmap_data
    result = track.binned_stats(tmp.name, bins, split=True, rpkm=rpkm)
  File "/home/ceang/anaconda3/envs/biofluff/lib/python2.7/site-packages/fluff/track.py", line 162, in binned_stats
    for feature, min_strand, plus_strand in self.fetch_to_counts(in_track):
  File "/home/ceang/anaconda3/envs/biofluff/lib/python2.7/site-packages/fluff/track.py", line 469, in fetch_to_counts
    for feature, features in self._get_features_by_feature(track):
  File "/home/ceang/anaconda3/envs/biofluff/lib/python2.7/site-packages/fluff/track.py", line 523, in _get_features_by_feature
    yield feature, features
UnboundLocalError: local variable 'feature' referenced before assignment

**Comment by simonvh** [comment]
I have tried to reproduce the error, but I can't. Can show me the top few lines of the input files (peaks and data files). Does it depend on one of the data files (A, B, C or D.bed) or does any one of these files result in this error? Do you have minimum example that you can give me?

**Comment by simonvh** [comment]
Closing due to inactivity, feel free to re-open if necessary.
