### ISSUE TITLE
could not reach the help section through -h argument

### ISSUE THREAD

**Issue by usobhi** [simonvh/fluff#75]
I have just installed fluff via pip and I tried to access the help section through `fluff heatmap -h` as mentioned in the commands section of docs; and I got the following error. I am still novice in using python based software and command lines.

Traceback (most recent call last):
  File "/bin/fluff", line 7, in <module>
    from fluff.parse import main
  File "/usr/lib/python2.7/site-packages/fluff/parse.py", line 4, in <module>
    from fluff.commands.heatmap import heatmap
  File "/usr/lib/python2.7/site-packages/fluff/commands/heatmap.py", line 15, in <module>
    from fluff.fluffio import load_heatmap_data, check_data
  File "/usr/lib/python2.7/site-packages/fluff/fluffio.py", line 13, in <module>
    from fluff.track import Track
  File "/usr/lib/python2.7/site-packages/fluff/track.py", line 91
    class Track(object, metaclass=TrackMeta):
                                 ^
SyntaxError: invalid syntax

**Comment by zqfang** [comment]
@usobhi , you need python 3 to install the latest version of fluff

**Comment by simonvh** [comment]
@usobhi for Python 2.7 you can install fluff version 2.1.4. Generally I would recommend you to move to Python 3 through, as all major libraries will soon drop support for Python 2. Alternatively, I can recommend [Anaconda + bioconda](http://bioconda.github.io/) for managing software. See the preprint here: https://www.biorxiv.org/content/early/2017/10/27/207092. Then you can also run Python 2 and Python 3 software in different environments.

**Comment by simonvh** [comment]
Closing due to inactivity, feel free to re-open if necessary.
