### ISSUE TITLE
Error when loading data, index error

### ISSUE THREAD

**Issue by KevinCheeseman** [simonvh/fluff#76]
Hello,

I have installed fluff using conda and tried it using the example dataset. Fluff works fine with it. 

However I get the following "Index error" error when I try it on my data. 

command line :
 fluff heatmap -f bed -d H3K18me1_smm.bam  H3K18ac_smm.bam -r -C k -k 5 -P 8 -o fluff_heatmap1.png

error message : 

euclidean distance method
Loading data
Error loading data in parallel, trying serial
Error: list index out of range
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/kev/anaconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/kev/anaconda3/lib/python3.6/site-packages/fluff/fluffio.py", line 159, in load_heatmap_data
    middle = int((int(vals[2]) + int(vals[1])) / 2)
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kev/anaconda3/lib/python3.6/site-packages/fluff/commands/heatmap.py", line 109, in load_data
    track, regions, profile, guard = job.get()
  File "/home/kev/anaconda3/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kev/anaconda3/bin/fluff", line 11, in <module>
    load_entry_point('biofluff==3.0.2', 'console_scripts', 'fluff')()
  File "/home/kev/anaconda3/lib/python3.6/site-packages/fluff/parse.py", line 349, in main
    heatmap(args)
  File "/home/kev/anaconda3/lib/python3.6/site-packages/fluff/commands/heatmap.py", line 139, in heatmap
    fragmentsize, dynam, guard)
  File "/home/kev/anaconda3/lib/python3.6/site-packages/fluff/commands/heatmap.py", line 117, in load_data
    fragmentsize, dynam, guard)
  File "/home/kev/anaconda3/lib/python3.6/site-packages/fluff/fluffio.py", line 159, in load_heatmap_data
    middle = int((int(vals[2]) + int(vals[1])) / 2)
IndexError: list index out of range

Hope you can help, 
Thanks in advance. 

Kevin.

**Comment by KevinCheeseman** [comment]
No problems. I finally found where the problem was this morning. The last line of my bed file ended with a newline. removing it did the trick. 

Thank you very much for taking the time to reply.
