### ISSUE TITLE
too many values to unpack

### ISSUE THREAD

**Issue by gk7279** [simonvh/fluff#77]
**fluff profile -i chr10:63319005-63381704,chr12:32819545-32853349 -d 1.bam 2.bam -a gene_models.bed -f 120 -n -s 1:2 -o output.png**
```
Traceback (most recent call last):
  File "/home/.local/bin/fluff", line 4, in <module>
    __import__('pkg_resources').run_script('biofluff==2.1.4', 'fluff')
  File "/home/python/2.7.13/lib/python2.7/site-packages/pkg_resources/__init__.py", line 743, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/python/2.7.13/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1498, in run_script
    exec(code, namespace, namespace)
  File "/home/.local/lib/python2.7/site-packages/biofluff-2.1.4-py2.7.egg/EGG-INFO/scripts/fluff", line 9, in <module>
    args.func(args)
  File "/home/.local/lib/python2.7/site-packages/biofluff-2.1.4-py2.7.egg/fluff/commands/profile.py", line 59, in profile
    adjscale=args.adjscale
  File "/home/.local/lib/python2.7/site-packages/biofluff-2.1.4-py2.7.egg/fluff/plot.py", line 283, in profile_screenshot
    chrom, start, end = re.split(r'[-:]', interval)
ValueError: too many values to unpack
```

**Comment by simonvh** [comment]
Sorry for the delay, I missed this somehow. In contrast to the documentation (oops!), `fluff profile` does not support multiple intervals at the moment. So you would have to run this in two commands:

```
fluff profile -i chr10:63319005-63381704 -d 1.bam 2.bam -a gene_models.bed -f 120 -n -s 1:2 -o output_1.png
```
```
fluff profile -i chr12:32819545-32853349 -d 1.bam 2.bam -a gene_models.bed -f 120 -n -s 1:2 -o output_2.png
```

**Comment by simonvh** [comment]
Closing due to inactivity, feel free to re-open if necessary.
