### ISSUE TITLE
fluff can't work

### ISSUE THREAD

**Issue by werhmk** [simonvh/fluff#78]
I download the test files and run the followed command on the Linux:

fluff profile -i chr1:68602071-68612071 -d mesenchymal_H3K27ac.bam mesendoderm_H3K27ac.bam -o test

The error was as followed, I don't know how to figure out,

Traceback (most recent call last):
  File "/home/hmk/anaconda2/bin/fluff", line 4, in <module>
    __import__('pkg_resources').run_script('biofluff==2.1.3', 'fluff')
  File "/home/hmk/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 654, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/hmk/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1434, in run_script
    exec(code, namespace, namespace)
  File "/home/hmk/anaconda2/lib/python2.7/site-packages/biofluff-2.1.3-py2.7.egg-info/scripts/fluff", line 9, in <module>
    args.func(args)
  File "/home/hmk/anaconda2/lib/python2.7/site-packages/fluff/commands/profile.py", line 59, in profile
    adjscale=args.adjscale
  File "/home/hmk/anaconda2/lib/python2.7/site-packages/fluff/plot.py", line 281, in profile_screenshot
    fig = plt.figure(figsize=(wsize, hsize))
  File "/home/hmk/anaconda2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 548, in figure
    **kwargs)
  File "/home/hmk/anaconda2/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/home/hmk/anaconda2/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 167, in new_figure_manager_given_figure
    canvas = cls.FigureCanvas(figure)
  File "/home/hmk/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 24, in __init__
    super(FigureCanvasQTAgg, self).__init__(figure=figure)
  File "/home/hmk/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 234, in __init__
    _create_qApp()
  File "/home/hmk/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 125, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable

**Comment by simonvh** [comment]
This is a problem with the default matplotlib configuration on a Linux server without an X environment. On the following page I give two possible solutions (for a different piece of software). Can you check if these work?
https://gimmemotifs.readthedocs.io/en/master/faq.html#faq

**Comment by simonvh** [comment]
I guess this issue is fixed? Feel free to reopen if you still encounter issues!
